apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-aspnetcore-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-aspnetcore-pod
  template:
    metadata:
      labels:
        app: demo-aspnetcore-pod
    spec:
      containers:
      - name: demo-aspnetcore-container
        image: demo-container:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
